# Bibliotecas e APIs

## 1 - LC | Numpy

Questão #1

Enunciado
Printe os elementos dos seguintes dois vetores usando apenas um for:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Depois, faça o mesmo usando numpy (usando a função nditer) e deixe um comentário sobre a diferença dos dois métodos.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [48]:
import numpy as np

arr = np.arange(50)

print('\nA)')
arr_atualizado = arr[arr % 2]
print(arr_atualizado)

print('\nB)')
arr_atualizado = arr[arr>5]
print(arr_atualizado)

print('\nC)')
arr_atualizado = arr[arr <= 10]
print(arr_atualizado)

print('\nD)')
arr_atualizado = arr[(arr != 1) | (arr != 3)]
print(arr_atualizado)


A)
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1]

B)
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

C)
[ 0  1  2  3  4  5  6  7  8  9 10]

D)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


Questão #2


Peça para o usuário uma lista com as comidas favoritas dele, depois transforme isso em um objeto numpy. Agora transformado, elimine todas as comidas que começam com uma vogal. Mostre o resultado.

Exemplo:

Entrada: [maçã, uva, morango, melancia, acelga]

Saída: [maçã, morango, melancia]

In [2]:
import numpy as np

print(frutas[sum([np.char.count(frutas, x) for x in 'aeiou']) == 2])


print('a) Crie um array aleatório de 15 itens entre 0 e 100;')
arr1 = np.random.randint(0, 100, 15)
print(arr1)

print('\nb) Qual o maior número do array?')
print(arr1.max())

print('\nc) Qual a sua posição?')
i, = np.where(arr1 == arr1.max())
print(i)


print('\nd) Verifique quais números do array são maior que 10;')
filter_arr = arr1 > 10
print(arr1[filter_arr])

print('\ne) Salve em uma nova lista apenas os itens entre 10 e 30.')
filter_arr = (arr1 > 10) & (arr1 < 30)
arr1[filter_arr]
print(arr1)


a) Crie um array aleatório de 15 itens entre 0 e 100;
[89 27 31 25  5  1 91 40 14 31  8 30 59 84 66]

b) Qual o maior número do array?
91

c) Qual a sua posição?
[6]

d) Verifique quais números do array são maior que 10;
[89 27 31 25 91 40 14 31 30 59 84 66]

e) Salve em uma nova lista apenas os itens entre 10 e 30.
[89 27 31 25  5  1 91 40 14 31  8 30 59 84 66]


Questão #3

Enunciado
Imprima a dimensão dos seguintes objetos numpy:

a = np.array(2)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [47]:
print('a)')
a = np.linspace(0, 100, 6, endpoint=True).reshape(3, 2)
print(a)
    
print('\nb)')
b = np.random.randint(100, size=(5, 2))
print(b)

print('\nc)')
print(b.reshape(2, 5))
np.matmul(a, b.reshape(2, 5))

a)
[[  0.  20.]
 [ 40.  60.]
 [ 80. 100.]]

b)
[[48 54]
 [75 16]
 [92 77]
 [56 40]
 [78 22]]

c)
[[48 54 75 16 92]
 [77 56 40 78 22]]


array([[ 1540.,  1120.,   800.,  1560.,   440.],
       [ 6540.,  5520.,  5400.,  5320.,  5000.],
       [11540.,  9920., 10000.,  9080.,  9560.]])

In [3]:
%%time
import random

n_sim = 10_000
agulhas = 1_000
x = np.random.random(agulhas * n_sim)
y = np.random.random(agulhas * n_sim)
dist = np.sqrt(x**2 + y**2) # (x**2 + y**2) ** 0.5
dentro = np.where(dist<=1, 1, 0)
pis_arr = dentro.reshape(n_sim, -1).mean(axis=1)*4


Wall time: 264 ms


In [ ]:
Questão #4

Enunciado
Transforme o array em uma matriz 4 por 3 utilizando numpy.

arr = [1, 2, 3, 4, 'Amelia, 'Bruna, 'Carolina', 'Débora', True, False, False, True]

Depois, faça o mesmo para uma matriz 3 por 4.