# Monitoria - 10-ago-2021

In [1]:
import numpy as np

In [27]:
y = np.arange(50)*3
y

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147])

In [43]:
y = np.array([10, 7.7, 6.7, 2])

In [34]:
((y > 30) & (y < 60)) | (y == 3)

array([False,  True, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [42]:
y[((y > 30) & (y < 60)) | (y == 3)]

array([ 3, 33, 36, 39, 42, 45, 48, 51, 54, 57])

In [44]:
y.mean()

6.6

In [45]:
y[(y != y.max()) & (y != y.min())].mean()

7.2

In [30]:
y % 4

array([0, 3, 2, 1, 0, 3, 2, 1, 0, 3, 2, 1, 0, 3, 2, 1, 0, 3, 2, 1, 0, 3,
       2, 1, 0, 3, 2, 1, 0, 3, 2, 1, 0, 3, 2, 1, 0, 3, 2, 1, 0, 3, 2, 1,
       0, 3, 2, 1, 0, 3])

In [31]:
y[y % 4]

array([0, 9, 6, 3, 0, 9, 6, 3, 0, 9, 6, 3, 0, 9, 6, 3, 0, 9, 6, 3, 0, 9,
       6, 3, 0, 9, 6, 3, 0, 9, 6, 3, 0, 9, 6, 3, 0, 9, 6, 3, 0, 9, 6, 3,
       0, 9, 6, 3, 0, 9])

In [18]:
y[np.array([0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]

array([0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])