# Monitoria 17-ago-2021

In [1]:
import numpy as np

In [4]:
a = np.arange(12)
a = a.reshape(2, 2, 3)

In [8]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
for i in a:
    print(i)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
for i in a:
    for j in i:
        print(j)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [16]:
for i in a:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [23]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            print(a[i][j][k])

0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
a.shape

(2, 2, 3)

In [24]:
len(a)

2

In [34]:
lista = []

for i in np.nditer(a):
    lista.append(i)
    
print(lista)

[array(0), array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8), array(9), array(10), array(11)]


In [35]:
lista = []

for i in np.nditer(a):
    lista.append(i.item())
    
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


----------------

Faça uma função que receba uma lista e conte quantas vezes cada elemento apareceu nessa 
lista. Essa função deverá guardar os dados em um dicionário no qual as chaves são os 
elementos da lista e os valores são a contagem de quantas vezes esse elemento aparece.

In [41]:
lista = ['a', 'a', 'b', 'c', 'c', 'c']

In [51]:
import random

lista_grande = [random.choice(['a', 'b', 'c']) for i in range(1_000_000)]

In [42]:
def conta_dicionario(lista):
    dicionario = {}
    
    for elemento in lista:
        if elemento in dicionario.keys():
            dicionario[elemento] += 1
        else:
            dicionario[elemento] = 1
            
    return dicionario

In [44]:
from collections import Counter

def conta_dicionario_2(lista):
    
    dicionario = dict(Counter(lista))
    
    return dicionario

In [54]:
%%timeit

conta_dicionario(lista_grande)

127 ms ± 573 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [55]:
%%timeit

conta_dicionario_2(lista_grande)

35.3 ms ± 837 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
