## Aula 1: Introdução ao Numpy e Pandas

### Bibliotecas usadas
As seguintes bibliotecas serão usadas:
 - Numpy;
 - Pandas.


## Códigos

### Numpy

Numpy é uma biblioteca das principais bibliotecas do Python, devido a sua grande velocidade e eficiência ele é extremamente utilizada para computação científica e analise de dados. Esta fama se da principalmente a estrutura chamada [numpy array](https://docs.scipy.org/doc/numpy/reference/arrays.html), um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

Abaixo começaremos o codigo passado em aula:

In [1]:
import numpy as np

#### Criando listas/vetores/arrays

In [2]:
lista = [1, 2, 10, 20, 34, 54]

In [3]:
lista

[1, 2, 10, 20, 34, 54]

In [4]:
vetor_numpy = np.array(lista)

In [5]:
vetor_numpy

array([ 1,  2, 10, 20, 34, 54])

In [6]:
type(vetor_numpy)

numpy.ndarray

In [7]:
n = 10
lista_zeros = [0] * n

In [9]:
print(lista_zeros)
print(len(lista_zeros))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
10


In [10]:
zeros = np.zeros(n)

In [14]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
uns = np.ones(n)

In [16]:
uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
cincos = np.ones(n) * 5

In [18]:
cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [19]:
cincos * 10

array([50., 50., 50., 50., 50., 50., 50., 50., 50., 50.])

In [20]:
lista_cincos = [5] * n

In [23]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [24]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [29]:
[x/20 for x in range(0, 21)]

[0.0,
 0.05,
 0.1,
 0.15,
 0.2,
 0.25,
 0.3,
 0.35,
 0.4,
 0.45,
 0.5,
 0.55,
 0.6,
 0.65,
 0.7,
 0.75,
 0.8,
 0.85,
 0.9,
 0.95,
 1.0]

In [38]:
np.linspace(0, 1, 21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [36]:
np.linspace(0, 1, 101)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [39]:
import random

In [41]:
random.randint(0, 100)

60

In [45]:
np.random.randint(0, 100)

45

In [46]:
type(np.random.randint(0, 100))

int

In [47]:
type(random.randint(0, 100))

int

In [66]:
%%time 
# Calculando o tempo de execução da célula utilizando o `%%time` funciona somente no jupyter e no ipython

# Gerando 10 inteiros aleatórios
np.random.randint(0, 100, 5000000)

CPU times: user 77.5 ms, sys: 11.6 ms, total: 89.1 ms
Wall time: 89.6 ms


array([17, 83, 91, ..., 94, 11, 89])

In [73]:
%%time
_ = [random.randint(0, 100) for n in range(0, 5000000)]

CPU times: user 3.05 s, sys: 20.1 ms, total: 3.07 s
Wall time: 3.07 s


#### Indexação

In [107]:
arr1 = np.random.randint(0, 100, 10000)

In [108]:
arr1

array([59, 93, 94, ..., 73, 68, 24])

In [109]:
arr1[0]

59

In [110]:
arr1[1: 4]

array([93, 94, 48])

In [111]:
arr1

array([59, 93, 94, ..., 73, 68, 24])

In [112]:
fatia = arr1[3: 8]

In [113]:
fatia

array([48, 19, 52, 62, 15])

#### Operações simples

In [114]:
%%time
arr1 * 20

CPU times: user 235 µs, sys: 150 µs, total: 385 µs
Wall time: 272 µs


array([1180, 1860, 1880, ..., 1460, 1360,  480])

In [115]:
lista1 = list(arr1)

In [116]:
%%time
[num * 20 for num in lista1]

CPU times: user 6.44 ms, sys: 216 µs, total: 6.65 ms
Wall time: 6.78 ms


[1180,
 1860,
 1880,
 960,
 380,
 1040,
 1240,
 300,
 1040,
 1120,
 1220,
 1820,
 1160,
 420,
 1340,
 680,
 1880,
 20,
 120,
 640,
 1480,
 1020,
 1300,
 1560,
 1220,
 1920,
 1460,
 1760,
 1760,
 1740,
 920,
 300,
 1140,
 1180,
 600,
 680,
 960,
 300,
 80,
 480,
 1080,
 220,
 1580,
 700,
 1420,
 1320,
 80,
 740,
 1640,
 720,
 1540,
 1560,
 20,
 40,
 480,
 740,
 1780,
 200,
 820,
 1520,
 1500,
 440,
 1240,
 860,
 560,
 1180,
 560,
 1300,
 380,
 460,
 720,
 1180,
 1540,
 680,
 1820,
 1640,
 1620,
 60,
 960,
 640,
 1360,
 740,
 40,
 1640,
 1340,
 600,
 780,
 980,
 1340,
 1480,
 100,
 420,
 900,
 1560,
 260,
 1780,
 640,
 1600,
 1680,
 960,
 1620,
 1360,
 1920,
 1920,
 1920,
 1260,
 960,
 1000,
 900,
 940,
 360,
 320,
 1580,
 180,
 1580,
 20,
 1520,
 1800,
 0,
 780,
 1620,
 1540,
 540,
 1720,
 800,
 700,
 1520,
 680,
 540,
 1540,
 1740,
 420,
 1880,
 880,
 1200,
 220,
 1080,
 1440,
 1120,
 1460,
 1560,
 580,
 680,
 580,
 620,
 380,
 1540,
 1120,
 640,
 540,
 380,
 200,
 600,
 340,
 640,
 46

In [117]:
arr1

array([59, 93, 94, ..., 73, 68, 24])

In [118]:
arr1 + 127

array([186, 220, 221, ..., 200, 195, 151])

In [119]:
arr1

array([59, 93, 94, ..., 73, 68, 24])

In [121]:
arr1 / 59

array([1.        , 1.57627119, 1.59322034, ..., 1.23728814, 1.15254237,
       0.40677966])

In [123]:
arr1 ** 3

array([205379, 804357, 830584, ..., 389017, 314432,  13824])

In [124]:
len(arr1)

10000

#### Operações com várias listas

In [126]:
arr1 = np.random.randint(0, 100, 10)
arr2 = np.random.randint(0, 100, 10)

In [127]:
arr1

array([71, 54, 98,  3, 15, 82, 49, 14, 75, 40])

In [128]:
arr2

array([13,  2, 63, 60, 34, 54, 84, 83, 11, 17])

In [129]:
arr1 + arr2

array([ 84,  56, 161,  63,  49, 136, 133,  97,  86,  57])

In [130]:
lista1 = list(arr1)
lista2 = list(arr2)

In [132]:
[num1 + num2 for num1, num2 in list(zip(arr1, arr2))]

[84, 56, 161, 63, 49, 136, 133, 97, 86, 57]

In [133]:
arr1 / arr2

array([ 5.46153846, 27.        ,  1.55555556,  0.05      ,  0.44117647,
        1.51851852,  0.58333333,  0.1686747 ,  6.81818182,  2.35294118])

In [134]:
arr1 * arr2

array([ 923,  108, 6174,  180,  510, 4428, 4116, 1162,  825,  680])

In [136]:
arr3 = np.random.randint(0, 100, 5)

In [137]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [138]:
arr1 * arr3

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

#### Métodos

In [143]:
# Retornando o valor máximo do array
arr1.max()

98

In [144]:
max(arr1)

98

In [148]:
arr1.argmax()

2

In [147]:
lista1.index(max(lista1))

2

In [149]:
arr1.min()

3

In [150]:
arr1.argmin()

3

In [152]:
arr1[arr1.argmin()]

3

In [153]:
arr1.sum()

501

In [154]:
arr1.mean()

50.1

In [155]:
arr1.std()

30.398848662408252

In [158]:
arr1.sort()

In [166]:
arr1

array([ 3, 14, 15, 40, 49, 54, 71, 75, 82, 98])

In [167]:
# Utilizando a função np.sort -> retorna o valor do array ordenado sem alterar a ordem
np.sort(arr2)

array([ 2, 11, 13, 17, 34, 54, 60, 63, 83, 84])

In [168]:
print(np.std(arr2))
print(np.sum(arr2))

29.06011011679068
421


In [172]:
arr4 = arr1 / 3

In [175]:
arr4.dtype

dtype('float64')

In [177]:
arr1.dtype

dtype('int64')

In [179]:
arr1

array([ 3, 14, 15, 40, 49, 54, 71, 75, 82, 98])

In [181]:
import sys
sys.getsizeof(arr1)

176

In [182]:
arr1.dtype

dtype('int64')

In [183]:
# Trocando o tipo de dados do array
arr5 = arr1.astype('int32')

In [184]:
arr5.dtype

dtype('int32')

In [185]:
sys.getsizeof(arr5)

136

In [186]:
arr6 = arr1.astype('int8')

In [187]:
sys.getsizeof(arr6)

106

In [188]:
lista_mista = [1, 10, 20.5, 30.2]

In [190]:
arr_misto = np.array(lista_mista)

In [191]:
arr_misto

array([ 1. , 10. , 20.5, 30.2])

In [192]:
arr_misto.dtype

dtype('float64')

In [194]:
arr_strings = np.array(['hoje', 'abacate', 'laranja'])

In [195]:
arr_strings

array(['hoje', 'abacate', 'laranja'], dtype='<U7')

In [196]:
arr_strings.dtype

dtype('<U7')

In [197]:
lista_mista = [1, 10.3, 'laranja']

In [199]:
arr_mista = np.array(lista_mista)

In [200]:
type(arr_mista)

numpy.ndarray

In [201]:
arr_mista.dtype

dtype('<U32')

In [208]:
sys.getsizeof(arr_mista)

480

In [207]:
# Precisamos transforma para objeto 
arr_mista.astype('object') * 3

array(['111', '10.310.310.3', 'laranjalaranjalaranja'], dtype=object)

In [210]:
arr_mista_obj = arr_mista.astype('object')
sys.getsizeof(arr_mista_obj)

120

In [203]:
'laranja' * 3

'laranjalaranjalaranja'

In [204]:
3 * 3

9

#### Matrix

In [221]:
arr_valores = np.arange(0, 20, 2)

In [222]:
arr_valores

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [223]:
matrix = arr_valores.reshape(5, 2)

In [217]:
# Quando imprimimos na tela aparece a matrix de forma agradável!
matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [232]:
# Na lista não

matrix.tolist() # transformando a matriz em uma lista de listas

[[0, 2], [4, 6], [8, 10], [12, 14], [16, 18]]

In [224]:
matrix.shape

(5, 2)

In [226]:
matrix.shape[0]

5

In [227]:
n_rows, n_cols = matrix.shape

In [233]:
# Criando uma matriz identidade
matriz_identidade = np.eye(5)

In [234]:
matriz_identidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [238]:
matrix[0][1]

2

In [241]:
matrix

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [239]:
matrix[2:]

array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [248]:
matrix[2: , 1:] # pegando a terceira linha em diante e a segunda coluna

array([[10],
       [14],
       [18]])

In [249]:
matrix[2:][ :  , # pegando todas as linhas
           1:] # pegando a terceira linha em diante. E depois todas as linhas e a segunda coluna.

array([[10],
       [14],
       [18]])

In [250]:
matriz_quadrada = np.array([[1000, 200], [2, -7]])

In [251]:
matriz_quadrada

array([[1000,  200],
       [   2,   -7]])

In [253]:
# Achando a determinante
np.linalg.det(matriz_quadrada)

-7400.0

In [255]:
inv_matriz_quadrada = np.linalg.inv(matriz_quadrada)

In [258]:
matriz_quadrada2 = np.array([[0,1], [1, 0]])

In [260]:
matriz_quadrada

array([[1000,  200],
       [   2,   -7]])

In [259]:
matriz_quadrada2

array([[0, 1],
       [1, 0]])

In [261]:
matriz_quadrada * matriz_quadrada2

array([[  0, 200],
       [  2,   0]])

```
[a, b] @ [e, f]  = [a*e + b*g, a*f + b*h]  
[c, d]   [g, h]    [c*e + d*g, c*f + d*h]  
```

In [262]:
# Utilizando o @ para fazer a multiplicação de matrizes
matriz_quadrada @ matriz_quadrada2

array([[ 200, 1000],
       [  -7,    2]])

In [263]:
# Podemos utilizar o matmul() para realizar a multiplicação de matrizes.
np.matmul(matriz_quadrada, matriz_quadrada2)

array([[ 200, 1000],
       [  -7,    2]])

In [264]:
vetor_3d = np.array([6400, 300, 200])

In [265]:
# Achando a norma de um vetor
np.linalg.norm(vetor_3d)

6410.148204214938

#### Máscaras

In [ ]:
# 39

In [ ]:
# 40

In [ ]:
# 41

In [ ]:
# 42